### ISSUE TITLE
On index page change the order of the products in tablet and mobile 

### ISSUE THREAD

**Issue by noamhoze** [droach587/walabot#2]
Since Pro and Starter are getting the best selling rates, 
we would like to show them first on mobile. 

* The order in desktop should stay the same - Starter, Maker and Pro.
* The order in tablet and mobile should be - Pro, Starter and Maker.

**Comment by droach587** [comment]
Please DO NOT make this change. This will affect the more than the visual and require 2 states for the code which is not recommended at all.

**Comment by droach587** [comment]
Closing this issue.

**Comment by noamhoze** [comment]
How would that affect more than the visual?

**Comment by droach587** [comment]
Change indicates re-ordering markup — if thats not the case we can re-open; however, the above indicates that markup will be turned on and off per viewport —— if its just copy, not an issue.

**Comment by noamhoze** [comment]
So lets me see if I understand, you suggest we use copying here (and toggle between visibility in different viewports)?

**Comment by noamhoze** [comment]
Merged to dev #3.
