### ISSUE TITLE
Remove "hand" pointer from an application panel once it is clicked

### ISSUE THREAD

**Issue by noamhoze** [droach587/walabot#5]
![image](https://cloud.githubusercontent.com/assets/20975533/18546842/daf00dda-7b48-11e6-8846-a7d6251cee47.png)

**Comment by droachrkn** [comment]
What is the purpose of this change ? You cannot remove the hand as the target is a link. This will break JS and css elsewhere on the site where I'm using this module. Furthermore as most users are on mobile / touch devices they never see a pointer, therefore this issue is irrelevant.
