### ISSUE TITLE
Separate mailing lists to users that registered for the newsletter from maker / DIY

### ISSUE THREAD

**Issue by noamhoze** [droach587/walabot#6]
For now there is one mailing list for users who registered to our newsletter either from the maker page or DIY page. 

Manage 2 separate lists.

**Comment by noamhoze** [comment]
@droach587, I simply replaced the `list_id` on `_updates_diy.php` to the "subscribers - DIY" list id on mail chimp. 
Is there anything I'm missing?

**Comment by droach587** [comment]
Should be good!

**Comment by noamhoze** [comment]
Fixed by #16.
